name: Tests

on: push

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up ruff
        uses: astral-sh/ruff-action@v3
      - name: Run linting
        run: ruff check
      - name: Check formatting
        run: ruff format --check --diff

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Check for unused code
        run: uv run vulture sodapy tests examples

      # not technically static analysis, but doesn't need to run across Python versions

      - name: Run Pyright
        run: uv run pyright

      - name: Confirm that package builds
        run: uv build

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
    continue-on-error: true
    env:
      PYTHON_VERSION: ${{ matrix.python-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Run tests and generate coverage report
        run: |
          uv run pytest \
            --cov --cov-branch --cov-report=xml \
            --junitxml=junit.xml -o junit_family=legacy

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          env_vars: PYTHON_VERSION
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
